### ISSUE TITLE
Module sizes

### ISSUE THREAD

**Issue by TrueCarry** [nonzzz/vite-bundle-analyzer#14]
Currently all npm packages have same size in UI, while some may be 10kb and others 1mb. Can you please make modules size based on their size in bundle? It works like that in webpack-bundle-analyzer

**Comment by TrueCarry** [comment]
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/73697325-4eb8-4a87-849b-f65b4b6bae85)
My report look like that
Here's 5mb package
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/31a04565-ad0b-45d3-9cb1-aad2286fdfdf)

And here's 18kb side by side
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/7be4d1ea-5c4f-40b1-b0e1-fbfc2b6d2801)

**Comment by nonzzz** [comment]
Thanks for your report. This feature will be implemented in the next version.

**Comment by nonzzz** [comment]
`0.7.0` has been released.

**Comment by TrueCarry** [comment]
Thank you very much! Works like expected. Not sure if related, but for some reason most modules lost their gzip and parsed sizes, only stat tab works.
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/67dcbf07-0d32-4c98-b257-fb974892fcf6)

Also for some reason vite outputs ?worker inputs as assets instead of chunks, not sure how can that be fixed, but because of that, we don't have workers in report

**Comment by nonzzz** [comment]
@TrueCarry The summary option will only add module information at the end. Like this

<img width="677" alt="image" src="https://github.com/nonzzz/vite-bundle-analyzer/assets/52351095/126c5d4f-7e7d-4785-9aae-b3fbfbebbd63">

**Comment by TrueCarry** [comment]
I've actually meant 2 different issues.
1.
Stat page:
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/2bf0580b-0bf1-4054-b064-b72baa4c0b8f)
Parsed page:
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/4729a10c-3434-45b0-8e02-7727ad77a82f)
Gzipped page:
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/0e13728c-e78e-4034-8936-d9eb9eb2b233)

As you see, gzipped and parsed pages are broken. I'm not sure that it's analyzer problem, maybe it's vite thing.

2. What I meant with ?worker. It is imported as `import Worker from '../executorWorker?worker'`. As you see on my screenshot from previous comment, I have ExecutorWorker.js that weights 5900kb, but it's not available in chunks list:
![image](https://github.com/nonzzz/vite-bundle-analyzer/assets/5431520/51d2ce3e-def1-487a-824a-6471769fa767)

I've checked vite output, and worker gets bundled as 'asset', not 'chunk', not sure how can that be addressed, but I don't think there's an easy way. 

I don't think both issues could be addressed without too much effort, so I just wanted to let you know about them. Thank you for your work!

**Comment by nonzzz** [comment]
In actuality, 'stat sizes' represents the size proximity to your native code (at least, that's my interpretation). However, I've observed that '?worker' does not appear in the 'parsed' or 'gzip' sizes (to be frank, there is currently no effective method to calculate this specific size). Vite is built on Rollup, where each chunk might be missing in the 'sourcemap' (resulting in the remaining chunks being merged by the analyzer). I believe switching to 'rolldown' in Vite might effectively address this issue.

As the documentation suggests, he just tries to analyze it as much as possible.

**Comment by nonzzz** [comment]
About [doc](https://vitejs.dev/guide/assets.html#importing-script-as-a-worker), I think vite don't put right chunk into bundle context, So I'm trying to get expect behavior from vite repl

**Comment by TrueCarry** [comment]
Parsed or gzip has no relation to worker. Even packages in index.js not listed there.

**Comment by nonzzz** [comment]
@TrueCarry I know, I'm planning resolve them at next version.
