### ISSUE TITLE
Request to add a configuration item. The default value for Treemap Sizes is Parsed

### ISSUE THREAD

**Issue by liub1934** [nonzzz/vite-bundle-analyzer#19]
<img width="430" alt="image" src="https://github.com/nonzzz/vite-bundle-analyzer/assets/29849550/5fc82425-f65a-4ce9-803f-79d744c28ad6">

**Comment by nonzzz** [comment]
This feature request AFAIk isn't a high priority. Currently i'm focus on the bundle size to same with the actual size.
