### ISSUE TITLE
Invalidate Option `analyzerMode` 打包报错

### ISSUE THREAD

**Issue by wumingluren** [nonzzz/vite-bundle-analyzer#23]
最新版
analyzer({
openAnalyzer: false, // 是否打开静态网站
}),
只配置了一个参数
  "devDependencies": {
    "@vitejs/plugin-legacy": "^5.3.2",
    "@vitejs/plugin-vue": "^5.0.4",
    "rollup-plugin-visualizer": "^5.12.0",
    "unplugin-auto-import": "^0.17.5",
    "unplugin-vue-components": "^0.26.0",
    "vite": "^5.2.9",
    "vite-bundle-analyzer": "^0.9.4",
    "vite-plugin-compression2": "^1.1.0"
  }

**Comment by nonzzz** [comment]
你需要写上`analyzerMode`

**Comment by wumingluren** [comment]
> 你需要写上`analyzerMode`

还以为会有默认值。看例子里面一个参数也没写
