### ISSUE TITLE
Static report does not work

### ISSUE THREAD

**Issue by jeron-diovis** [nonzzz/vite-bundle-analyzer#29]
Version 0.10.2

Just running build with `analyzer({ analyzerMode: 'static' })` plugin. 
Stats file is generated, but opening it gives blank page and this error:

<img width="616" alt="Screenshot 2024-06-18 at 14 46 44" src="https://github.com/nonzzz/vite-bundle-analyzer/assets/2756868/ff95e6a7-7f1b-4760-af47-b12ed5ec8dfe">

In server mode, UI opens normally.

**Comment by nonzzz** [comment]
When i migrate vite's version cause it. A fix version has been released. Try `0.10.3`

**Comment by jeron-diovis** [comment]
All good now. Thanks!
