### ISSUE TITLE
error in use MUI

### ISSUE THREAD

**Issue by xellosiris** [nonzzz/vite-bundle-analyzer#31]
when I try build project and it appears error msg below:

node_modules/@mui/material/AccordionDetails/AccordionDetails.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@mui/material/AccordionSummary/AccordionSummary.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@mui/material/AlertTitle/AlertTitle.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@mui/material/AppBar/AppBar.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@mui/material/Alert/Alert.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.
node_modules/@mui/material/Autocomplete/Autocomplete.js (1:0): Error when using sourcemap for reporting an error: Can't resolve original location of error.

....etc

**Comment by nonzzz** [comment]
I create a simple repo in my local. Console is full of noise, but interesting to be able generate analyze report.

**Comment by nonzzz** [comment]
This is not a plugin bug. Related https://github.com/vitejs/vite/issues/15012

**Comment by xellosiris** [comment]
got it, thank you
