### ISSUE TITLE
Is it possible to package the library without compressing the source code?

### ISSUE THREAD

**Issue by a145789** [nonzzz/vite-bundle-analyzer#32]
When the plugin reports an error, it jumps from `cmd` to the source code error message, a friendly context that can help developers quickly locate the problem.

![image](https://github.com/user-attachments/assets/b98590be-7388-4d58-8d67-1c8c2423d48c)

![image](https://github.com/user-attachments/assets/388d2204-54c2-4e53-bb75-f8b0b9d57bbf)

**Comment by nonzzz** [comment]
When i publish this package, i wonder a minimalist package so i compress the code. According the error message. It's seems like provide an unsupported `analyzerMode`. By the way. If you want to debug this package. you can setup `vite build --debug` or `set ANALYZE_DEBUG=true && vite build`
