### ISSUE TITLE
Parsed and Gzipped sizes are zero

### ISSUE THREAD

**Issue by rulila52** [nonzzz/vite-bundle-analyzer#34]
I'm included this plugin in my vite project with minimal configuration and try to make static output. When i open static stats.html, i see correst Stat sizes, but on tabs Parsed and Gzipped i see 0 bytes for all chunk. Is it bug or i do something wrong?

**Comment by nonzzz** [comment]
It's work well in my local. If the parsed or gzip size is zero. I think you can try to provide a debug info.


```bash

$ vite build --debug

# Or use the following method
# darwin / linux

$ export ANALYZE_DEBUG=true && vite build

# window

$ set ANALYZE_DEBUG=true && vite build


# Or using cross-env

```


Then you'll see all of debug info and paste in here.

**Comment by nonzzz** [comment]
AFAIk, If you're using vite's legacy plugin. The legacy chunk isn't provide any sourcemap So that those module isn't be scan.

**Comment by nonzzz** [comment]
I'm using `vite-plugin-legacy-swc` to test the legacy generate. But i got the following sourcemap

```json

{"version":3,"file":"x-legacy-5cb72e43.js","sources":[],"sourcesContent":[],"names":[],"mappings":""}

```

**Comment by nonzzz** [comment]
@faga295 Any other informations? Such as using based on the vite framework or your config workspaces plugins. AFAIK only `Chunk status` and `Sourcemap status` both as truthy can work.

**Comment by faga295** [comment]
I tried updating my Vite version and found that this plugin works only with versions 4.0.0 and above.

**Comment by nonzzz** [comment]
@faga295 Butt i think the minimum requirement is to support vite@3. So what's your past vite version?

**Comment by faga295** [comment]
3.1.0

**Comment by nonzzz** [comment]
I know, but i'm not sure it can resolve this problem. [relative release](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#features-22)

**Comment by nonzzz** [comment]
@faga295 I release `v0.12.0` i think it can be support. Can you have a try?

**Comment by faga295** [comment]
It works

**Comment by nonzzz** [comment]
But now i'd like to close this issue, if there are any problems re open it again.
