### ISSUE TITLE
Feature request: openAnalyzer for static mode

### ISSUE THREAD

**Issue by tocque** [nonzzz/vite-bundle-analyzer#37]
### Describe the feature request

Bundle analyzer for webpack allow generate a report into disk and open it in browser immediately. I think it is useful. Maybe you can let openAnalyzer work with static mode.

**Comment by nonzzz** [comment]
Sound well

**Comment by nonzzz** [comment]
It's support now. A new version will be released.

**Comment by nonzzz** [comment]
`v0.11.0` is released now!
