### ISSUE TITLE
openAnalyzer: false is ignored

### ISSUE THREAD

**Issue by vxsx** [nonzzz/vite-bundle-analyzer#38]
### Describe the issue

with the configuration 

```
      analyzer({ analyzerMode: 'static', openAnalyzer: false }),
```

the server starts, instead of finishing the build

### Expected behavior

It still runs the server, because `preferOpenServer` is true even if `openAnalyzer` is false

https://github.com/nonzzz/vite-bundle-analyzer/blob/7da1da7000d64b936d9e07ec18986a9b50d18699/src/server/index.ts#L71-L72

### Steps to reproduce

Just run the build with this configuration.

**Comment by vxsx** [comment]
I understand starting the server and opening browser are slightly different things, but i expect "static" mode to not start the server. 

I believe the fix would be just to add the condition 

```ts
const preferOpenServer = opts.analyzerMode === 'server' || (opts.analyzerMode === 'static' && opts.openAnalyzer)
```
```

**Comment by nonzzz** [comment]
@vxsx You're right. my mistake.

**Comment by vxsx** [comment]
Yup, works with the new version. Thanks a lot!
