### ISSUE TITLE
Refactor client display

### ISSUE THREAD

**Issue by nonzzz** [nonzzz/vite-bundle-analyzer#41]
### Describe the feature request

Now we use `foam tree` as us data display. But i create a new project `squarified` is same as `foam tree` and the size can reduce `200kb`. I'm not sure if it's a good idea.

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/98e1736b-9691-41fe-83ea-fe2b2642424e">

**Comment by nonzzz** [comment]
@SukkaW CC

**Comment by SukkaW** [comment]
https://airbnb.io/visx/treemap

What about this then? But we might have to bring other packages for tooltip.

**Comment by nonzzz** [comment]
We can implement tooltip by ourselves by just getting the coordinates of the rect. By the way. [squarified](https://github.com/nonzzz/squarified) provide these functions.

**Comment by nonzzz** [comment]
I think `squarified` can replace `@foam/tree` now although they don't seem like same. ( The theme system will be updated later but i think the current default `rainbow` color is enough.

![image](https://github.com/user-attachments/assets/da463e2e-735c-4a32-94bd-554395c7a42d)
