### ISSUE TITLE
[Vite 6] [vite-bundle-anlyzer] Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by budarin** [nonzzz/vite-bundle-analyzer#47]
### Describe the issue

while building a project using vite 6, I get this error

### Expected behavior

no errors

### Steps to reproduce

- upgrade or create project with vite 6
- add vite-bundle-analyzer plugin to vite's config
- try to build

**Comment by nonzzz** [comment]
plugin version?
https://stackblitz.com/edit/vitejs-vite-gatwhm?file=package.json,vite.config.ts,README.md&terminal=dev

**Comment by budarin** [comment]
> plugin version? https://stackblitz.com/edit/vitejs-vite-gatwhm?file=package.json,vite.config.ts,README.md&terminal=dev

0.12.1

**Comment by nonzzz** [comment]
Upgrade this plugin. AFAIK `vite6` break a lot of logic.
